# Generated by Django 4.1.4 on 2022-12-25 06:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=256, verbose_name='عنوان')),
                ('slug', models.SlugField(max_length=256, unique=True, verbose_name='آدرس')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها'
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='عنوان')),
                ('author', models.CharField(max_length=256, verbose_name='نویسنده')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('image', models.ImageField(upload_to='images/', verbose_name='عکس')),
                ('slug', models.SlugField(max_length=256, unique=True, verbose_name='آدرس')),
                ('price', models.IntegerField(verbose_name='قیمت')),
                ('in_stock', models.BooleanField(default=True, verbose_name='موجود در انبار')),
                ('is_active', models.BooleanField(default=True, verbose_name='نمایش دادن')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ افزودن')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='آخرین دستکاری')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='shop.category', verbose_name='دسته بندی')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_creator', to=settings.AUTH_USER_MODEL, verbose_name='تولید شده توسط')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
            },
        ),
    ]
